name: mcmc_yplus-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pymc>=5
  - pip
  - scipy
  - scikit-learn
  - graphviz
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets